In [1]:
import numpy as np

In [3]:
a = np.array([[4,6,7,8],[9,10,11,12]])
a.ndim

2

In [4]:
a

array([[ 4,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
z = np.zeros(7)
z

array([0., 0., 0., 0., 0., 0., 0.])

In [9]:
print(a)
t = a.T
t

[[ 4  6  7  8]
 [ 9 10 11 12]]


array([[ 4,  9],
       [ 6, 10],
       [ 7, 11],
       [ 8, 12]])

In [11]:
a.shape

(2, 4)

In [12]:
r = a.reshape(4,2)
r

array([[ 4,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
c = np.array([3,4,5,6,8])

In [14]:
np.mean(c)

5.2

In [15]:
np.median(c)

5.0